In [3]:
#https://github.com/IST256/learn-python/blob/master/content/lessons/12/Now-You-Code/NYC4-Exam-Scores.ipynb
import pandas as pd
URL='https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv'

In [6]:
df = pd.read_csv(URL)
df.head(5)aaaa

,Class Section,Exam Version,Completion Time,Made Own Study Guide,Did Exam Prep Assignment,Studied In Groups,Student Score,Percentage,Letter Grade
0,M01,A,20,N,N,Y,24,80.00%,B
1,M01,A,20,?,?,?,27,90.00%,A-
2,M01,A,30,Y,Y,Y,30,100.00%,A
3,M01,A,50,N,Y,Y,18,60.00%,C-
4,M01,A,55,Y,Y,N,24,80.00%,B

In [7]:
Class_Section = 'M01'
Exam_version = 'A'

In [17]:
#With valid inputs it should filter the DataFrame to only those rows matching the input (for example section M01, version A)

df_filter = df[(df['Class Section'] == Class_Section) & (df['Exam Version'] == Exam_version) ]
df_filter

,Class Section,Exam Version,Completion Time,Made Own Study Guide,Did Exam Prep Assignment,Studied In Groups,Student Score,Percentage,Letter Grade
0,M01,A,20,N,N,Y,24,80.00%,B
1,M01,A,20,?,?,?,27,90.00%,A-
2,M01,A,30,Y,Y,Y,30,100.00%,A
3,M01,A,50,N,Y,Y,18,60.00%,C-
4,M01,A,55,Y,Y,N,24,80.00%,B
5,M01,A,60,N,Y,Y,25,83.30%,B
6,M01,A,60,Y,Y,Y,30,100.00%,A

In [22]:
#And display only the Student Score and Letter Grade for each student matching the inputs.
df_few_fields = df_filter[['Student Score','Letter Grade']]
df_few_fields

   Student Score Letter Grade
0             24            B
1             27           A-
2             30            A
3             18           C-
4             24            B
5             25            B
6             30            A

In [25]:
from Ipython.display import display

ModuleNotFoundError: No module named 'Ipython'

In [28]:
from ipywidgets import widgets
test = widgets.Text